
# AUTOGRADING CONFIGURATION FOR Danielle's CP222
[default]
course-id = 43491
course-name = "Danielle's CP222"
module-name = "cp222/2023_block2"
unit-test-dir = "/packages/mcscn/cp222/2023b2_cp222/bin"

# perhaps there should be an id mapping instead...

[155997]
assignment-name = "Recall JAVA"
language = "java"

[155997.pipeline]
# should we be able to accept multiple inputs?
input="first_assignment.zip"

[[155997.pipeline.steps]]
type="UnzipDirectory"


[[155997.pipeline.steps]]
type="ValidateDirectory"
max_score=0.5
root="first_assignment"
paths=["test/FirstTest.java", "src/First.java", "src/FirstI.java", "src/FirstException.java", "src/RunFirst.java"]

[[155997.pipeline.steps]]
type="JavaDoc"
max_score = 0.5
files = ["src/First.java"]

[[155997.pipeline.steps]]
type = "Compile"
max_score = 0
source= ["test/FirstTest.java", "src/First.java", "src/FirstI.java", "src/FirstException.java", "src/RunFirst.java"]
[[155997.pipeline.steps]]
max_score = 3
type = "JUnit"
test = "test/FirstTest.java"
testTypes = {"fillArray" = 1, "filename" = 1, "seekLetter" = 1}
# possible way for doing end-to-end tests
# steps = [
#     {type = "unzip" },
   # {type = "directory", paths = ["test/FirstTest.java", "src/First.java", "src/FirstI.java", "src/FirstException.java", "src/RunFirst.java"], value = 0.5},
#     {type = "javadoc", paths = ["src/First.java"], value = 0.5},
#     {type = "unit-tests", path = "first_assignment/test/FirstTest.java", tests = {"fillArray" = 1, "filename" = 1, "seekLetter" = 1}},
# ]
[155990]
assignment-name = "Debugger Maze"
language = "Java"
[155990.pipeline]

[[155990.pipeline.steps]]
type="UnzipDirectory"

[[155990.pipeline.steps]]
type="ValidateDirectory"
max_score=1
root="maze"
paths=["moves.txt", "README.txt", "src/DoneBrokeException.java", "src/InvalidMoveException.java", "src/MazeGenerator.java","src/Maze.java", "src/Room.java"]

[[155990.pipeline.steps]]
type = "Compile"
max_score = 0
source= ["src/DoneBrokeException.java", "src/InvalidMoveException.java", "src/MazeGenerator.java", "src/Maze.java", "src/Room.java"]

[[155990.pipeline.steps]]
type = "EndToEnd"
max_score = 3
command = "java -cp out Maze"
reqs = {"Oh no! No tea and no Alex!"= 1,"Oh no! You didn't find Alex with the tea... and now the tea is cold!" = 2, "Yay! You have a tea party with Alex!" = 3}

[155972]
assignment-name = "DFA Library"

[155972.pipeline]

[155996]
assignment-name = "Macro Assembler"

[155996.pipeline]

[155991]
assignment-name = "Exceptional Work"

[155991.pipeline]

[155971]
assignment-name = "DFA Application"

[155971.pipeline]

[155998]
assignment-name = "Regular Expressions"

[155998.pipeline]

[155992]
assignment-name = "JAVA Diagram 1"

[155992.pipeline]

[155993]
assignment-name = "JAVA Diagram 2"

[155993.pipeline]

[155994]
assignment-name = "JAVA Diagram 3"

[155994.pipeline]

[155995]
assignment-name = "JAVA Diagram 4"

[155995.pipeline]

[155973]
assignment-name = "Day 1"

[155973.pipeline]

[155982]
assignment-name = "Day 2"

[155982.pipeline]

[155983]
assignment-name = "Day 3"

[155983.pipeline]

[155984]
assignment-name = "Day 4"

[155984.pipeline]

[155985]
assignment-name = "Day 5"

[155985.pipeline]

[155986]
assignment-name = "Day 6"

[155986.pipeline]

[155987]
assignment-name = "Day 7"

[155987.pipeline]

[155988]
assignment-name = "Day 8"

[155988.pipeline]

[155989]
assignment-name = "Day 9"

[155989.pipeline]

[155974]
assignment-name = "Day 10"

[155974.pipeline]

[155975]
assignment-name = "Day 11"

[155975.pipeline]

[155976]
assignment-name = "Day 12"

[155976.pipeline]

[155977]
assignment-name = "Day 13"

[155977.pipeline]

[155978]
assignment-name = "Day 14"

[155978.pipeline]

[155979]
assignment-name = "Day 15"

[155979.pipeline]

[155980]
assignment-name = "Day 16"

[155980.pipeline]

[155981]
assignment-name = "Day 17"

[155981.pipeline]
